//! Generated Hermes plugin template rendering.
//!
//! This module owns the generated Python/YAML/Markdown source strings emitted by
//! `tracedecay install --agent hermes`, keeping the installer flow in
//! `super::write_plugin_files` focused on filesystem orchestration.

use crate::errors::{Result, TraceDecayError};
use crate::mcp::tools::{format_capable_tool_names, get_tool_definitions};

pub(super) fn plugin_manifest() -> String {
    let tools = get_tool_definitions()
        .into_iter()
        .map(|tool| format!("  - {}", tool.name))
        .collect::<Vec<_>>()
        .join("\n");
    // `version` tracks the generating binary so `hermes plugins list` and
    // `tracedecay doctor` can detect stale generated plugins after upgrades.
    format!(
        "name: tracedecay\n\
         kind: standalone\n\
         version: {version}\n\
         generator_commit: {commit}\n\
         description: TraceDecay code-graph tools, memory provider, and LCM context engine for Hermes\n\
         author: tracedecay (generated by `tracedecay install --agent hermes`)\n\
         provides_tools:\n{tools}\n\
         provides_hooks:\n\
           - pre_llm_call\n\
         provides_commands:\n\
           - /tracedecay_status\n",
        version = env!("CARGO_PKG_VERSION"),
        commit = env!("TRACEDECAY_GIT_SHA"),
    )
}

pub(super) fn plugin_schemas() -> String {
    r#""""Generated tracedecay tool schemas for Hermes."""
import json
from pathlib import Path

with Path(__file__).with_name("schemas.json").open("r", encoding="utf-8") as schema_file:
    TOOL_SCHEMAS = json.load(schema_file)
"#
    .to_string()
}

pub(super) fn plugin_schemas_json() -> Result<String> {
    let defs = get_tool_definitions()
        .into_iter()
        .map(|tool| {
            serde_json::json!({
                "name": tool.name,
                "description": tool.description,
                "parameters": tool.input_schema,
            })
        })
        .collect::<Vec<_>>();
    serde_json::to_string_pretty(&defs)
        .map(|json| format!("{json}\n"))
        .map_err(|e| TraceDecayError::Config {
            message: format!("failed to serialize Hermes schemas.json: {e}"),
        })
}

pub(super) fn plugin_tools(tracedecay_bin: &str) -> String {
    let bin =
        serde_json::to_string(tracedecay_bin).unwrap_or_else(|_| "\"tracedecay\"".to_string());
    let format_tools = format_capable_tool_names()
        .iter()
        .map(|name| format!("    {name:?},"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#""""Generated tracedecay tool handlers for Hermes."""
import json
import os
import subprocess
import tempfile

TRACEDECAY_BIN = {bin}
# Default per-call ceiling. Long-running verbs (LCM ingest/compression over
# long transcripts, doctor/diagnose repair passes) keep a higher ceiling.
TRACEDECAY_TIMEOUT_SECONDS = 120
TRACEDECAY_LONG_TIMEOUT_SECONDS = 600
LONG_RUNNING_TOOLS = frozenset((
    "tracedecay_lcm_compress",
    "tracedecay_lcm_preflight",
    "tracedecay_lcm_doctor",
    "tracedecay_diagnose",
    # First hermes search runs the state.db catch-up sweep, which can
    # exceed the default ceiling on large profile histories.
    "tracedecay_message_search",
))
MAX_CAPTURE_CHARS = 4000
# Linux caps a single argv string at MAX_ARG_STRLEN (128 KiB). Payloads at or
# above this threshold spill to a tempfile passed as `--args @<path>` so
# compression of exactly the long sessions it exists for cannot fail with
# E2BIG/EFAULT at exec time.
ARGS_FILE_THRESHOLD_BYTES = 100000

# Profile-state tools: memory facts and transcript search use the active
# pinned/resolved project when available, falling back to the Hermes profile
# home only for unpinned profiles.
PROFILE_STORE_TOOLS = frozenset((
    "tracedecay_fact_store",
    "tracedecay_fact_feedback",
    "tracedecay_memory_status",
    "tracedecay_message_search",
    "tracedecay_lcm_status",
    "tracedecay_lcm_doctor",
    "tracedecay_lcm_load_session",
    "tracedecay_lcm_grep",
    "tracedecay_lcm_describe",
    "tracedecay_lcm_expand",
    "tracedecay_lcm_expand_query",
    "tracedecay_lcm_preflight",
    "tracedecay_lcm_compress",
    "tracedecay_lcm_session_boundary",
))
JSON_FORMAT_TOOLS = frozenset((
{format_tools}
))

_PLUGIN_CONFIG_CACHE = {{}}

def hermes_home_dir(hermes_home=None):
    return str(
        hermes_home
        or os.environ.get("HERMES_HOME")
        or os.path.join(os.path.expanduser("~"), ".hermes")
    )

def plugin_config_block(hermes_home=None):
    """Return the `plugins.tracedecay` mapping from the profile config.yaml.

    This is the conventional Hermes home for plugin settings (the same
    `plugins.<name>` block bundled plugins use). Cached per config file
    mtime so the hot tool-dispatch path stays cheap.
    """
    home = hermes_home_dir(hermes_home)
    path = os.path.join(home, "config.yaml")
    try:
        stat = os.stat(path)
        cache_key = (stat.st_mtime_ns, stat.st_size)
    except OSError:
        return {{}}
    cached = _PLUGIN_CONFIG_CACHE.get(path)
    if cached is not None and cached[0] == cache_key:
        return cached[1]
    block = {{}}
    try:
        import yaml
        with open(path, encoding="utf-8-sig") as config_file:
            config = yaml.safe_load(config_file) or {{}}
        plugins = config.get("plugins")
        candidate = plugins.get("tracedecay") if isinstance(plugins, dict) else None
        if isinstance(candidate, dict):
            block = candidate
    except Exception:
        block = {{}}
    _PLUGIN_CONFIG_CACHE[path] = (cache_key, block)
    return block

def config_pinned_project_root(hermes_home=None):
    value = plugin_config_block(hermes_home).get("project_root")
    if not (isinstance(value, str) and value.strip()):
        return None
    pin = value.strip()
    # Legacy installs pinned the Hermes home itself as the "project" — that
    # was a storage-home conflation, not a code project, so a home-equal pin
    # is treated as no pin at all.
    try:
        if os.path.realpath(pin) == os.path.realpath(hermes_home_dir(hermes_home)):
            return None
    except OSError:
        pass
    return pin

def config_terminal_cwd(hermes_home=None):
    home = hermes_home_dir(hermes_home)
    path = os.path.join(home, "config.yaml")
    try:
        import yaml
        with open(path, encoding="utf-8-sig") as config_file:
            config = yaml.safe_load(config_file) or {{}}
        terminal = config.get("terminal")
        value = terminal.get("cwd") if isinstance(terminal, dict) else None
    except Exception:
        return None
    return value.strip() if isinstance(value, str) and value.strip() else None

def _has_tracedecay_index(path):
    if not (isinstance(path, str) and path.strip() and os.path.isabs(path)):
        return False
    return os.path.isdir(os.path.join(path, ".tracedecay"))

def code_project_root(explicit=None, cwd=None, hermes_home=None):
    if explicit:
        return str(explicit)
    session_cwd = cwd or config_terminal_cwd(hermes_home)
    if _has_tracedecay_index(session_cwd):
        return str(session_cwd)
    pin = config_pinned_project_root(hermes_home)
    if pin:
        return pin
    if isinstance(session_cwd, str) and os.path.isabs(session_cwd):
        return session_cwd
    return None

def normalize_output(value) -> str:
    if value is None:
        return ""
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    return str(value)

def truncate_output(value, limit: int = MAX_CAPTURE_CHARS) -> str:
    output = normalize_output(value)
    if len(output) <= limit:
        return output
    return output[:limit] + "...<truncated>"

def error_payload(message: str, result=None) -> str:
    payload = {{"error": message}}
    if result is not None:
        stdout = truncate_output(getattr(result, "stdout", ""))
        stderr = truncate_output(getattr(result, "stderr", ""))
        if stdout:
            payload["stdout"] = stdout
        if stderr:
            payload["stderr"] = stderr
    return json.dumps(payload)

def call_tracedecay_tool(name: str, args: dict, **kwargs) -> str:
    args_file = None
    try:
        tool_args = args or {{}}
        if name in JSON_FORMAT_TOOLS and "format" not in tool_args:
            tool_args = dict(tool_args)
            tool_args["format"] = "json"
        if "messages" in kwargs and "messages" not in tool_args:
            tool_args = dict(tool_args)
            tool_args["messages"] = kwargs["messages"]
        # Project routing:
        #   1. An explicit per-call project_root (call kwarg / tool arg)
        #      wins for every tool.
        #   2. Hermes state tools use the active code project when one is
        #      pinned/resolved, so LCM and memory share the unified
        #      user-level tracedecay store for that project.
        #   3. Unpinned Hermes profile-store calls use the hermes_profile
        #      storage scope instead of synthesizing a project root.
        project_root = kwargs.get("project_root") or tool_args.get("project_root")
        if not project_root and tool_args.get("storage_scope") == "hermes_profile":
            project_root = None
        if not project_root and tool_args.get("storage_scope") != "hermes_profile":
            project_root = code_project_root(cwd=kwargs.get("cwd") or tool_args.get("cwd"))
            if not project_root and name in PROFILE_STORE_TOOLS:
                tool_args = dict(tool_args)
                tool_args.setdefault("storage_scope", "hermes_profile")
                tool_args.setdefault("hermes_home", hermes_home_dir())
                project_root = None
        payload = json.dumps(tool_args)
        argv = [TRACEDECAY_BIN, "tool"]
        if project_root:
            argv.extend(["--project", str(project_root)])
        argv.extend([name, "--json", "--args"])
        if len(payload.encode("utf-8")) >= ARGS_FILE_THRESHOLD_BYTES:
            fd, args_file = tempfile.mkstemp(prefix="tracedecay-args-", suffix=".json")
            with os.fdopen(fd, "w", encoding="utf-8") as args_handle:
                args_handle.write(payload)
            argv.append("@" + args_file)
        else:
            argv.append(payload)
        timeout_seconds = (
            TRACEDECAY_LONG_TIMEOUT_SECONDS
            if name in LONG_RUNNING_TOOLS
            else TRACEDECAY_TIMEOUT_SECONDS
        )
        result = subprocess.run(
            argv,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            shell=False,
        )
        if result.returncode != 0:
            return error_payload(f"tracedecay tool exited with status {{result.returncode}}", result)
        output = result.stdout.strip()
        if not output:
            return "{{}}"
        try:
            json.loads(output)
            return output
        except json.JSONDecodeError:
            return error_payload("tracedecay tool returned invalid JSON", result)
    except subprocess.TimeoutExpired as exc:
        return error_payload("tracedecay tool timed out", exc)
    except Exception as exc:
        return json.dumps({{"error": f"tracedecay tool failed: {{exc}}"}})
    finally:
        if args_file is not None:
            try:
                os.unlink(args_file)
            except OSError:
                pass

def make_handler(name: str):
    def handler(args: dict, **kwargs) -> str:
        return call_tracedecay_tool(name, args, **kwargs)
    return handler
"#
    )
}

/// Generated `__init__.py` body, embedded from `templates/plugin_init.py` so
/// the Python payload lives as an editable asset instead of a giant Rust
/// string literal. Copied verbatim (no interpolation) below the provenance
/// header.
const PLUGIN_INIT_BODY_PY: &str = include_str!("templates/plugin_init.py");

pub(super) fn plugin_init() -> String {
    // Provenance header: lets `tracedecay doctor` and humans detect a live
    // install that was clobbered by an older/newer generator build.
    format!(
        "# Generated by tracedecay {} (commit {}). Do not edit; refresh with `tracedecay update-plugin`.\n{body}",
        env!("CARGO_PKG_VERSION"),
        env!("TRACEDECAY_GIT_SHA"),
        body = PLUGIN_INIT_BODY_PY,
    )
}

/// `hermes tracedecay ...` CLI passthrough. Hermes' memory-plugin CLI
/// discovery (`plugins/memory/__init__.py::discover_plugin_cli_commands`)
/// loads `cli.py` from the ACTIVE provider's directory and wires
/// `register_cli(subparser)` + `tracedecay_command(args)` into argparse, so
/// the verbs work without any core change (honcho pattern).
pub(super) const PLUGIN_CLI_PY: &str = include_str!("templates/cli.py");

pub(super) const HERMES_SKILL: &str = include_str!("templates/skill.md");
