[profile.ci]
fail-fast = false
retries = 0
flaky-result = "fail"
slow-timeout = { period = "10s", terminate-after = 36 }
final-status-level = "slow"

[[profile.ci.overrides]]
filter = 'all()'
platform = { host = 'cfg(windows)' }
retries = 2
flaky-result = 'pass'
