#!/usr/bin/env bash
# End-to-end proof that `tracedecay install --agent hermes` works against
# STOCK (upstream NousResearch/hermes-agent) Hermes — not just customized
# forks. Used by the `hermes-integration` CI job and runnable locally:
#
#   git clone https://github.com/NousResearch/hermes-agent.git /tmp/hermes-upstream
#   git -C /tmp/hermes-upstream checkout <pinned ref>
#   cargo build --bin tracedecay
#   scripts/hermes_stock_integration.sh
#
# Environment:
#   TRACEDECAY_BIN        tracedecay binary to install/test (default: target/debug/tracedecay)
#   HERMES_UPSTREAM_DIR  stock hermes-agent checkout (default: /tmp/hermes-upstream)
#
# Everything is offline and deterministic: a throwaway HERMES_HOME and a
# throwaway initialized project, no model calls, no network beyond whatever
# `uv sync` needs the first time the upstream venv is created.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TRACEDECAY_BIN="${TRACEDECAY_BIN:-$REPO_ROOT/target/debug/tracedecay}"
TRACEDECAY_BIN="$(cd "$(dirname "$TRACEDECAY_BIN")" && pwd)/$(basename "$TRACEDECAY_BIN")"
HERMES_UPSTREAM_DIR="${HERMES_UPSTREAM_DIR:-/tmp/hermes-upstream}"

if [ ! -x "$TRACEDECAY_BIN" ]; then
    echo "error: tracedecay binary not found at $TRACEDECAY_BIN (build with: cargo build --bin tracedecay)" >&2
    exit 1
fi
if [ ! -f "$HERMES_UPSTREAM_DIR/pyproject.toml" ]; then
    echo "error: stock hermes-agent checkout not found at $HERMES_UPSTREAM_DIR" >&2
    exit 1
fi

echo "== stock hermes ref: $(git -C "$HERMES_UPSTREAM_DIR" rev-parse HEAD 2>/dev/null || echo unknown)"
echo "== tracedecay binary: $TRACEDECAY_BIN ($("$TRACEDECAY_BIN" --version))"

# Upstream venv with upstream's exact-pinned lock (idempotent).
if [ ! -x "$HERMES_UPSTREAM_DIR/.venv/bin/python" ]; then
    echo "== creating stock hermes venv (uv sync --frozen --no-dev)"
    (cd "$HERMES_UPSTREAM_DIR" && uv sync --frozen --no-dev)
fi
HERMES_PYTHON="$HERMES_UPSTREAM_DIR/.venv/bin/python"

STAGE="$(mktemp -d -t hermes-stock-XXXXXX)"
trap 'rm -rf "$STAGE"' EXIT
FAKE_HOME="$STAGE/home"
PROJECT="$STAGE/project"
mkdir -p "$FAKE_HOME" "$PROJECT/src"

# Throwaway project so tool dispatch has a real .tracedecay graph to hit.
printf 'pub fn add(a: i32, b: i32) -> i32 { a + b }\n\npub fn double(x: i32) -> i32 { add(x, x) }\n' > "$PROJECT/src/lib.rs"
printf '[package]\nname = "throwaway"\nversion = "0.1.0"\nedition = "2021"\n' > "$PROJECT/Cargo.toml"
git -C "$PROJECT" init -q
git -C "$PROJECT" add -A
git -C "$PROJECT" -c user.email=ci@tracedecay -c user.name=ci commit -qm init
(cd "$PROJECT" && HOME="$FAKE_HOME" "$TRACEDECAY_BIN" init)

echo "== tracedecay install --agent hermes"
HOME="$FAKE_HOME" "$TRACEDECAY_BIN" install --agent hermes --project-root "$PROJECT"
HERMES_HOME="$FAKE_HOME/.hermes"
test -f "$HERMES_HOME/plugins/tracedecay/plugin.yaml"

echo "== stock plugin manager / context engine / memory provider / dispatch checks"
(
    cd "$HERMES_UPSTREAM_DIR" &&
        HOME="$FAKE_HOME" HERMES_HOME="$HERMES_HOME" TRACEDECAY_PROJECT_ROOT="$PROJECT" \
            "$HERMES_PYTHON" "$REPO_ROOT/scripts/hermes_stock_check.py"
)

echo "== hermes plugins list"
PLUGINS_LIST="$(cd "$HERMES_UPSTREAM_DIR" && HOME="$FAKE_HOME" HERMES_HOME="$HERMES_HOME" COLUMNS=200 \
    timeout 120 "$HERMES_UPSTREAM_DIR/.venv/bin/hermes" plugins list)"
echo "$PLUGINS_LIST" | grep tracedecay
echo "$PLUGINS_LIST" | grep tracedecay | grep -q enabled
echo "ok - hermes plugins list shows tracedecay enabled"

echo "== tracedecay doctor"
DOCTOR_OUT="$(cd "$PROJECT" && HOME="$FAKE_HOME" HERMES_HOME="$HERMES_HOME" "$TRACEDECAY_BIN" doctor 2>&1)"
echo "$DOCTOR_OUT" | grep -q "Hermes tracedecay plugin found"
if echo "$DOCTOR_OUT" | grep -q "was generated by tracedecay"; then
    echo "error: doctor reports a stale generated plugin:" >&2
    echo "$DOCTOR_OUT" | grep "was generated by tracedecay" >&2
    exit 1
fi
if echo "$DOCTOR_OUT" | grep -q "pins project_root"; then
    echo "error: doctor reports a broken project_root pin:" >&2
    echo "$DOCTOR_OUT" | grep "pins project_root" >&2
    exit 1
fi
echo "ok - tracedecay doctor Hermes section is clean"

echo "stock hermes integration: PASS"
