//! Hermes agent integration.
//!
//! Installs a Hermes profile plugin that exposes tracedecay tools as
//! Hermes-native plugin tools.

mod dashboard_wrapper;
mod lifecycle;
mod profile_config;
mod tokensave_migration;

use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use crate::errors::{Result, TraceDecayError};
pub(crate) use profile_config::read_config_pinned_project_root;
use profile_config::{disable_plugin, effective_pinned_project_root, enable_plugin};

use super::{
    AgentIntegration, DoctorCounters, HealthcheckContext, InstallContext, UpdatePluginOutcome,
};

mod templates;

/// Hermes agent.
pub struct HermesIntegration;

impl AgentIntegration for HermesIntegration {
    fn name(&self) -> &'static str {
        "Hermes"
    }

    fn id(&self) -> &'static str {
        "hermes"
    }

    fn install(&self, ctx: &InstallContext) -> Result<()> {
        lifecycle::install(ctx)?;
        Ok(())
    }

    fn supports_local_install(&self) -> bool {
        true
    }

    fn install_local(&self, ctx: &InstallContext, project_path: &Path) -> Result<()> {
        lifecycle::install_local(ctx, project_path)?;
        Ok(())
    }

    fn update_plugin(&self, ctx: &InstallContext) -> Result<UpdatePluginOutcome> {
        lifecycle::update_plugin(ctx)
    }

    fn uninstall(&self, ctx: &InstallContext) -> Result<()> {
        lifecycle::uninstall(ctx)?;
        Ok(())
    }

    fn healthcheck(&self, dc: &mut DoctorCounters, ctx: &HealthcheckContext) {
        eprintln!("\n\x1b[1mHermes integration\x1b[0m");
        doctor_check_plugin(dc, &ctx.home, &ctx.project_path);
    }

    fn is_detected(&self, home: &Path) -> bool {
        hermes_home(home).is_dir()
    }

    fn primary_config_path(&self, home: &Path) -> Option<PathBuf> {
        Some(hermes_profile_dir(home, None).join("config.yaml"))
    }

    fn has_tracedecay(&self, home: &Path) -> bool {
        let locations = tokensave_migration::profile_locations(home, None);
        locations.plugin_dir.join("plugin.yaml").exists()
            || locations.legacy_plugin_dir.join("plugin.yaml").exists()
    }
}

fn hermes_home(home: &Path) -> PathBuf {
    home.join(".hermes")
}

fn hermes_profile_dir(home: &Path, profile: Option<&str>) -> PathBuf {
    match profile {
        Some(profile) => hermes_home(home).join("profiles").join(profile),
        None => hermes_home(home),
    }
}

// Profile names are deliberately restricted to ASCII `[a-z0-9][a-z0-9_-]`:
// non-ASCII names are rejected outright (clear error below), so Unicode
// normalization concerns (NFC vs NFD on macOS filesystems producing
// colliding/diverging directory names) cannot arise by construction.
pub(super) fn normalize_profile(profile: Option<&str>) -> Result<Option<String>> {
    let Some(profile) = profile else {
        return Ok(None);
    };
    let normalized = profile.to_ascii_lowercase();
    let mut chars = normalized.chars();
    let valid = normalized.len() <= 64
        && chars
            .next()
            .is_some_and(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit())
        && chars.all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_' || ch == '-');
    if !valid {
        return Err(TraceDecayError::Config {
            message: format!(
                "invalid Hermes profile '{profile}': expected [a-z0-9][a-z0-9_-]{{0,63}}"
            ),
        });
    }
    Ok(Some(normalized))
}

fn doctor_check_plugin(dc: &mut DoctorCounters, home: &Path, project_path: &Path) {
    let candidates = hermes_healthcheck_plugin_paths(home, project_path);
    let existing: Vec<&PathBuf> = candidates.iter().filter(|plugin| plugin.exists()).collect();
    let Some(first) = existing.first() else {
        if let Some(plugin) = candidates.first() {
            dc.warn(&format!(
                "{} not found — run `tracedecay install --agent hermes` if you use Hermes",
                plugin.display()
            ));
        } else {
            dc.warn("Hermes tracedecay plugin not found — run `tracedecay install --agent hermes` if you use Hermes");
        }
        return;
    };
    dc.pass(&format!(
        "Hermes tracedecay plugin found at {}",
        first.display()
    ));

    for manifest_path in &existing {
        let Some(plugin_dir) = manifest_path.parent() else {
            continue;
        };
        // Stale generated plugins keep working but miss new tools/config
        // surfaces; `hermes plugins list` shows the same manifest version.
        match read_manifest_version(manifest_path) {
            Some(version) if version == env!("CARGO_PKG_VERSION") => {}
            Some(version) => dc.warn(&format!(
                "{} was generated by tracedecay {version} (installed binary is {}) — re-run `tracedecay install --agent hermes` to refresh it",
                manifest_path.display(),
                env!("CARGO_PKG_VERSION"),
            )),
            None => dc.warn(&format!(
                "{} has no manifest version — re-run `tracedecay install --agent hermes` to refresh it",
                manifest_path.display(),
            )),
        }
        // A pinned project that no longer exists makes every Hermes tool
        // call fail; surface it here instead of at first tool use.
        if let Some(pin) = effective_pinned_project_root(plugin_dir) {
            if !Path::new(&pin).is_dir() {
                dc.warn(&format!(
                    "{} pins project_root {pin}, which does not exist — re-run `tracedecay install --agent hermes --project-root <path>`",
                    plugin_dir.display(),
                ));
            }
        }
    }
}

fn hermes_healthcheck_plugin_paths(home: &Path, project_path: &Path) -> Vec<PathBuf> {
    let mut roots = Vec::new();
    roots.push(hermes_home(home));

    if let Some(env_home) = std::env::var_os("HERMES_HOME") {
        if !env_home.is_empty() {
            roots.push(PathBuf::from(env_home));
        }
    }

    roots.extend(hermes_profile_dirs(home));
    roots.push(project_path.join(".hermes"));

    let mut seen = std::collections::BTreeSet::new();
    let mut plugins = Vec::new();
    for root in roots {
        let plugin = root.join("plugins/tracedecay/plugin.yaml");
        if seen.insert(plugin.clone()) {
            plugins.push(plugin);
        }
    }
    plugins
}

fn hermes_profile_dirs(home: &Path) -> Vec<PathBuf> {
    let profiles_dir = hermes_home(home).join("profiles");
    let Ok(entries) = std::fs::read_dir(&profiles_dir) else {
        return Vec::new();
    };
    let mut profiles = entries
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let file_type = entry.file_type().ok()?;
            file_type.is_dir().then(|| entry.path())
        })
        .collect::<Vec<_>>();
    profiles.sort();
    profiles
}

fn read_manifest_version(manifest_path: &Path) -> Option<String> {
    let manifest = std::fs::read_to_string(manifest_path).ok()?;
    manifest
        .lines()
        .find_map(|line| line.strip_prefix("version:"))
        .map(|version| version.trim().to_string())
        .filter(|version| !version.is_empty())
}

pub(super) fn install_plugin(
    plugin_dir: &Path,
    tracedecay_bin: &str,
    project_root: Option<&Path>,
    deploy_dashboard: bool,
) -> Result<()> {
    // An explicit pin wins; otherwise preserve whatever pin a previous
    // install wrote to the config block, so `tracedecay reinstall` does not
    // silently unpin.
    let pinned_project_root = match project_root {
        Some(path) => Some(path.display().to_string()),
        None => effective_pinned_project_root(plugin_dir),
    };
    write_plugin_files(plugin_dir, tracedecay_bin)?;
    dashboard_wrapper::apply_install_policy(
        plugin_dir,
        tracedecay_bin,
        pinned_project_root.as_deref(),
        deploy_dashboard,
    )?;
    if let Some(profile_dir) = plugin_dir.parent().and_then(Path::parent) {
        let config_path = profile_dir.join("config.yaml");
        enable_plugin(&config_path, pinned_project_root.as_deref())?;
    }

    eprintln!(
        "\x1b[32m✔\x1b[0m Wrote Hermes tracedecay plugin to {}",
        plugin_dir.display()
    );
    Ok(())
}

/// Writes the generated agent-plugin files (manifest, schemas, tools,
/// entrypoint, skill). Shared by install and the config-preserving update
/// lifecycle path; never touches config.yaml.
pub(super) fn write_plugin_files(plugin_dir: &Path, tracedecay_bin: &str) -> Result<()> {
    std::fs::create_dir_all(plugin_dir).map_err(|e| TraceDecayError::Config {
        message: format!("failed to create {}: {e}", plugin_dir.display()),
    })?;
    std::fs::create_dir_all(plugin_dir.join("skills/tracedecay")).map_err(|e| {
        TraceDecayError::Config {
            message: format!(
                "failed to create {}: {e}",
                plugin_dir.join("skills/tracedecay").display()
            ),
        }
    })?;

    write_text_file(
        &plugin_dir.join("plugin.yaml"),
        &templates::plugin_manifest(),
    )?;
    write_text_file(&plugin_dir.join("schemas.py"), &templates::plugin_schemas())?;
    write_text_file(
        &plugin_dir.join("schemas.json"),
        &templates::plugin_schemas_json()?,
    )?;
    write_text_file(
        &plugin_dir.join("tools.py"),
        &templates::plugin_tools(tracedecay_bin),
    )?;
    write_text_file(&plugin_dir.join("__init__.py"), &templates::plugin_init())?;
    write_text_file(&plugin_dir.join("cli.py"), templates::PLUGIN_CLI_PY)?;
    write_text_file(
        &plugin_dir.join("skills/tracedecay/SKILL.md"),
        templates::HERMES_SKILL,
    )
}

/// Plugin directories with a detected generated install (a `plugin.yaml`
/// manifest), deduplicated across the default profile, named profiles,
/// `HERMES_HOME`, and the current directory's project-local `.hermes`.
/// Legacy `TokenSave` manifests are mapped to their steady-state tracedecay
/// plugin directory so refreshes write current artifacts in-place.
pub(super) fn detected_plugin_dirs(home: &Path) -> Vec<PathBuf> {
    let mut roots = vec![hermes_home(home)];
    if let Some(env_home) = std::env::var_os("HERMES_HOME") {
        if !env_home.is_empty() {
            roots.push(PathBuf::from(env_home));
        }
    }
    roots.extend(hermes_profile_dirs(home));
    if let Ok(cwd) = std::env::current_dir() {
        roots.push(cwd.join(".hermes"));
    }

    let mut seen = std::collections::BTreeSet::new();
    roots
        .into_iter()
        .filter_map(|root| {
            let plugin_dir = tokensave_migration::detected_plugin_dir(&root)?;
            seen.insert(plugin_dir.clone()).then_some(plugin_dir)
        })
        .collect()
}

pub(super) fn uninstall_plugin(plugin_dir: &Path) -> Result<()> {
    if let Some(profile_dir) = plugin_dir.parent().and_then(Path::parent) {
        disable_plugin(&profile_dir.join("config.yaml"))?;
    }
    remove_generated_plugin_files(plugin_dir)
}

pub(super) fn remove_generated_plugin_files(plugin_dir: &Path) -> Result<()> {
    if !plugin_dir.exists() {
        eprintln!("  {} not found, skipping", plugin_dir.display());
        return Ok(());
    }

    remove_generated_file(&plugin_dir.join("plugin.yaml"))?;
    remove_generated_file(&plugin_dir.join("schemas.py"))?;
    remove_generated_file(&plugin_dir.join("schemas.json"))?;
    remove_generated_file(&plugin_dir.join("tools.py"))?;
    remove_generated_file(&plugin_dir.join("__init__.py"))?;
    remove_generated_file(&plugin_dir.join("cli.py"))?;
    remove_generated_file(&plugin_dir.join("skills/tracedecay/SKILL.md"))?;
    remove_generated_file(&plugin_dir.join("skills/tokensave/SKILL.md"))?;
    remove_empty_dir(&plugin_dir.join("skills/tracedecay"))?;
    remove_empty_dir(&plugin_dir.join("skills/tokensave"))?;
    remove_empty_dir(&plugin_dir.join("skills"))?;
    dashboard_wrapper::uninstall(plugin_dir)?;

    if remove_empty_dir(plugin_dir)? {
        eprintln!(
            "\x1b[32m✔\x1b[0m Removed Hermes tracedecay plugin from {}",
            plugin_dir.display()
        );
    } else {
        eprintln!(
            "  Left {} in place because it contains files not generated by tracedecay",
            plugin_dir.display()
        );
    }
    Ok(())
}

pub(super) fn write_text_file(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| TraceDecayError::Config {
            message: format!("failed to create {}: {e}", parent.display()),
        })?;
    }
    let current = std::fs::read_to_string(path).unwrap_or_default();
    if current == contents {
        return Ok(());
    }
    // Write-to-.new-then-rename so a mid-write crash can never leave a
    // truncated/corrupt generated file behind (same pattern as
    // write_config_file, minus the backup — these files are regenerable).
    let new_path = PathBuf::from(format!("{}.new", path.display()));
    if let Err(e) = std::fs::write(&new_path, contents) {
        std::fs::remove_file(&new_path).ok();
        return Err(TraceDecayError::Config {
            message: format!("failed to write {}: {e}", new_path.display()),
        });
    }
    if let Err(e) = std::fs::rename(&new_path, path) {
        std::fs::remove_file(&new_path).ok();
        return Err(TraceDecayError::Config {
            message: format!(
                "failed to replace {} with {}: {e}",
                path.display(),
                new_path.display()
            ),
        });
    }
    Ok(())
}

pub(super) fn remove_generated_file(path: &Path) -> Result<()> {
    match std::fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == ErrorKind::NotFound => Ok(()),
        Err(e) => Err(TraceDecayError::Config {
            message: format!("failed to remove {}: {e}", path.display()),
        }),
    }
}

pub(super) fn remove_empty_dir(path: &Path) -> Result<bool> {
    match std::fs::remove_dir(path) {
        Ok(()) => Ok(true),
        Err(e) if matches!(e.kind(), ErrorKind::NotFound | ErrorKind::DirectoryNotEmpty) => {
            Ok(false)
        }
        Err(e) => Err(TraceDecayError::Config {
            message: format!("failed to remove {}: {e}", path.display()),
        }),
    }
}
