/**
 * Dev entry for the dashboard frontend.
 *
 * The SDK and plugin registry are installed on window before any plugin entry
 * is dynamically imported. Dev keeps the real React module instead of the prod
 * SDK shim because react-dom/client needs React internals, and the single
 * Rsbuild graph already shares one React instance.
 */

import { useState, useEffect, useSyncExternalStore } from "react";
import { createRoot } from "react-dom/client";
import { buildSDK } from "../shell/src/sdk.jsx";

// Shell theme tokens + SDK component classes (.ts-*). Plugin CSS layers below
// consume the same CSS variables.
import "../shell/src/styles.css";
import "../lib/primitives.css";
import "../graph/src/styles.css";
import "../code-diagnostics/src/styles.css";
import "../savings/src/styles.css";
import "../lcm/src/styles.css";
// Holographic styles are generated by dev/run.mjs with the same Tailwind v4
// compiler path as production before Rsbuild resolves this import.
import "../holographic/dist/style.css";

// Type-only: the standalone shell (shell/src/main.jsx) and this dev entry both
// install the Hermes plugin SDK + registry on `window`. Declared loose (`any`)
// because the SDK is a host-provided bag of React/hooks/components/utils.
declare global {
  interface Window {
    __HERMES_PLUGIN_SDK__: any;
    __HERMES_PLUGINS__: any;
  }
}

// ---------------------------------------------------------------------------
// SDK + plugin registry — populated BEFORE plugin entries are imported.
// ---------------------------------------------------------------------------

window.__HERMES_PLUGIN_SDK__ = buildSDK();

const registered = new Map<string, any>();
const listeners = new Set<() => void>();
let registryVersion = 0;

function notify() {
  registryVersion += 1;
  for (const fn of listeners) {
    try {
      fn();
    } catch {
      /* listener errors must not break registration */
    }
  }
}

window.__HERMES_PLUGINS__ = {
  register(name: string, component: any) {
    registered.set(name, component);
    notify();
  },
  registerSlot() {},
};

function useRegistryVersion() {
  return useSyncExternalStore(
    (fn) => {
      listeners.add(fn);
      return () => listeners.delete(fn);
    },
    () => registryVersion,
    () => registryVersion,
  );
}

// Apply the dark theme early so the first paint matches the shell.
try {
  document.documentElement.setAttribute("data-theme", "dark");
} catch {
  /* non-browser */
}

// ---------------------------------------------------------------------------
// Plugin discovery + registration (dynamic, fault-tolerant).
// ---------------------------------------------------------------------------

const PLUGIN_ENTRIES = [
  { name: "holographic", load: () => import("../holographic/src/entry") },
  { name: "graph", load: () => import("../graph/src/entry") },
  { name: "code-diagnostics", load: () => import("../code-diagnostics/src/entry") },
  { name: "savings", load: () => import("../savings/src/entry") },
  { name: "hermes-lcm", load: () => import("../lcm/src/entry") },
];

async function loadPlugins() {
  await Promise.all(
    PLUGIN_ENTRIES.map(async (p) => {
      try {
        await p.load();
        return;
      } catch (err) {
        // Rsbuild leaves a stack in `err`; keep the console line scannable.
        console.warn(`[tracedecay dev] failed to load "${p.name}":`, err);
      }
      console.warn(`[tracedecay dev] plugin "${p.name}" has no loadable entry — skipping.`);
    }),
  );
}

// Fire-and-forget: registrations update the UI live via useRegistryVersion.
loadPlugins();

// ---------------------------------------------------------------------------
// Minimal dev shell: a tab bar over the registered plugin components.
// Intentionally smaller than prod's App (no URL sync, polling, or asset
// injection) — plugins are imported by the dev bundle, not fetched.
// ---------------------------------------------------------------------------

const PLUGIN_LABELS = {
  holographic: "Holographic Memory",
  graph: "Code Graph",
  "code-diagnostics": "Code Diagnostics",
  savings: "Savings & Cost",
  "hermes-lcm": "LCM",
};

function App() {
  useRegistryVersion();
  const names = Array.from(registered.keys());
  const [active, setActive] = useState("");

  useEffect(() => {
    if ((!active || !registered.has(active)) && names.length > 0) {
      setActive(names[0]);
    }
  }, [names, active]);

  const tabs = names.map((n) => ({ name: n, label: PLUGIN_LABELS[n] || n }));
  const Active = active ? registered.get(active) : null;

  return (
    <div className="ts-shell">
      <header className="ts-shell-header">
        <div className="ts-shell-brand">
          <span className="ts-shell-logo" aria-hidden="true">
            ◳
          </span>
          <h1 className="ts-shell-title">tracedecay · dev</h1>
        </div>
        <div className="ts-shell-tabs" role="tablist" aria-label="Plugin tabs (dev)">
          {tabs.map((t) => (
            <button
              key={t.name}
              type="button"
              role="tab"
              aria-selected={t.name === active}
              tabIndex={t.name === active ? 0 : -1}
              className={`ts-shell-tab${t.name === active ? " ts-shell-tab-active" : ""}`}
              onClick={() => setActive(t.name)}
            >
              {t.label}
            </button>
          ))}
          {tabs.length === 0 && (
            <span style={{ padding: "0.5rem 1rem", color: "var(--ts-text-3)" }}>
              No plugins registered…
            </span>
          )}
        </div>
      </header>
      <main className="ts-shell-main">
        {Active ? (
          <Active />
        ) : (
          <div className="ts-shell-loading" role="status" aria-live="polite">
            Waiting for plugins to register…
          </div>
        )}
      </main>
    </div>
  );
}

createRoot(document.getElementById("root")).render(<App />);
